# Generated by Django 5.2.7 on 2025-10-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('posting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('main_tasks', models.TextField()),
                ('requirements', models.TextField()),
                ('preferred_points', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('career_min', models.IntegerField()),
                ('career_max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('content', models.TextField(help_text='이력서 원본 내용')),
                ('content_hash', models.CharField(help_text='이력서 내용 해시값', max_length=64)),
                ('analysis_result', models.JSONField(blank=True, help_text='이력서 분석 결과 (캐시)', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='마지막 분석 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rank', models.IntegerField(help_text='추천 순위 (1-10)')),
                ('match_score', models.FloatField(help_text='매칭 점수')),
                ('match_reason', models.TextField(help_text='추천 이유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.jobposting')),
            ],
            options={
                'ordering': ['user_id', 'rank'],
                'unique_together': {('user_id', 'rank', 'created_at')},
            },
        ),
    ]
