# Generated by Django 5.2.7 on 2025-11-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="job_posting",
        ),
        migrations.AlterUniqueTogether(
            name="jobrecommendation",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
        migrations.DeleteModel(
            name="JobPosting",
        ),
        migrations.DeleteModel(
            name="JobRecommendation",
        ),
    ]
