# Generated by Django 5.2.7 on 2025-11-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0005_alter_jobrecommendation_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("rank", models.IntegerField(help_text="추천 순위 (1-10)")),
                ("match_score", models.FloatField(help_text="매칭 점수")),
                ("match_reason", models.TextField(help_text="추천 이유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.jobposting"
                    ),
                ),
            ],
            options={
                "db_table": "agent_job_recommendation",
                "ordering": ["user_id", "rank"],
                "unique_together": {("user_id", "rank", "created_at")},
            },
        ),
    ]
