# Generated by Django 5.2.8 on 2025-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="프롬프트 이름 (예: 기술 면접관)", max_length=100
                    ),
                ),
                ("content", models.TextField(help_text="프롬프트 내용")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_recommendation_prompt",
                "ordering": ["-created_at"],
            },
        ),
    ]
