# Generated by Django 5.2.8 on 2026-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAuthorizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("google", "Google")], max_length=20),
                ),
                ("state", models.CharField(max_length=128, unique=True)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("code_verifier", models.CharField(max_length=200)),
                ("code_challenge", models.CharField(max_length=200)),
                (
                    "code_challenge_method",
                    models.CharField(default="S256", max_length=10),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "state"],
                        name="user_oautha_provide_c26ac6_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="user_oautha_expires_0e7262_idx"
                    ),
                    models.Index(
                        fields=["used_at"], name="user_oautha_used_at_f71105_idx"
                    ),
                ],
            },
        ),
    ]
