# Generated by Django 5.2.8 on 2026-01-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_oauthauthorizationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("google", "Google")], max_length=20),
                ),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "subject"],
                        name="user_userso_provide_0a0fdc_idx",
                    ),
                    models.Index(fields=["email"], name="user_userso_email_4e7eff_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"),
                        name="uniq_social_provider_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uniq_social_user_provider"
                    ),
                ],
            },
        ),
    ]
