# Generated by Django 5.2.8 on 2026-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_usersocialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
