# Generated by Django 5.2.7 on 2025-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="skills_preferred",
            field=models.JSONField(
                blank=True, help_text="우대 기술 스택 (JSON 배열)", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_required",
            field=models.JSONField(
                blank=True, help_text="요구 기술 스택 (JSON 배열)", null=True
            ),
        ),
    ]
