# Generated by Django 5.2.7 on 2025-11-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_jobposting_skills_preferred_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="experience_summary",
            field=models.TextField(
                blank=True, help_text="경력 요약 (임베딩용)", null=True
            ),
        ),
    ]
