# Generated by Django 5.2.7 on 2025-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_resume_experience_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="skills_preferred",
            field=models.TextField(blank=True, help_text="우대 사항 원문", null=True),
        ),
    ]
