# Generated by Django 5.2.7 on 2025-11-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_jobposting_skills_preferred"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="jobrecommendation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="job_posting",
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
        migrations.DeleteModel(
            name="JobRecommendation",
        ),
    ]
