# Generated by Django 5.2.8 on 2026-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_jobrecommendation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="category",
            field=models.JSONField(
                blank=True, help_text="카테고리 (JSON 배열)", null=True
            ),
        ),
    ]
