# Generated by Django 5.2.8 on 2026-01-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_jobposting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="preferred_points",
            field=models.TextField(blank=True, null=True),
        ),
    ]
