# Generated by Django 5.2.8 on 2026-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_alter_jobposting_preferred_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="career_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="career_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="main_tasks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
