# Generated by Django 5.2.7 on 2025-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("content", models.TextField(help_text="이력서 원본 내용")),
                (
                    "content_hash",
                    models.CharField(help_text="이력서 내용 해시값", max_length=64),
                ),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, help_text="이력서 분석 결과 (캐시)", null=True
                    ),
                ),
                (
                    "experience_summary",
                    models.TextField(
                        blank=True, help_text="경력 요약 (임베딩용)", null=True
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, help_text="마지막 분석 시간", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_resume",
            },
        ),
    ]
