# Generated by Django 5.2.7 on 2025-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="content_hash",
            field=models.CharField(
                blank=True, help_text="이력서 내용 해시값", max_length=64, null=True
            ),
        ),
    ]
