# Generated by Django 5.2.7 on 2025-11-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_alter_resume_content_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
