# Generated by Django 5.2.7 on 2025-11-25 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_alter_resume_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="title",
            field=models.CharField(
                default="내 이력서", help_text="이력서 제목", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
