# Generated by Django 5.2.7 on 2025-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_resume_title_alter_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="대표 이력서 여부 (추천 대상)"
            ),
        ),
    ]
