# Generated by Django 5.2.8 on 2026-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_resume_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="analyzed_content_hash",
            field=models.CharField(
                blank=True,
                help_text="마지막 분석 시점의 content_hash (변경 감지용)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="last_process_task_id",
            field=models.CharField(
                blank=True,
                help_text="마지막 이력서 처리(Celery) task_id",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="last_process_task_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="마지막 이력서 처리(Celery) task_id 갱신 시간",
                null=True,
            ),
        ),
    ]
